AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal Pipeline Pulse Infrastructure - S3 only with unique naming'

Parameters:
  DomainName:
    Type: String
    Default: '1chsalesreports.com'
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: [dev, staging, prod]
  
Resources:
  # S3 Bucket for Frontend with unique naming
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DomainName}-frontend-${Environment}-${AWS::AccountId}-${AWS::Region}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: pipeline-pulse

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'

Outputs:
  FrontendBucketName:
    Description: Frontend S3 Bucket Name
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-Frontend-Bucket'
  
  FrontendBucketWebsiteURL:
    Description: Frontend S3 Bucket Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-Frontend-URL'
  
  FrontendBucketDomainName:
    Description: Frontend S3 Bucket Domain Name
    Value: !GetAtt FrontendBucket.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-Frontend-Domain'
