AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL setup for Pipeline Pulse (single AZ)'

Parameters:
  StackName:
    Type: String
    Default: 'pipeline-pulse-infrastructure'
  DBUsername:
    Type: String
    Default: 'postgres'
    Description: 'Database master username'
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'Database master password'
    MinLength: 8

Resources:
  # Create a second subnet in a different AZ for RDS requirement
  SecondSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-bed99dc6
      CidrBlock: 172.31.128.0/24
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: pipeline-pulse-rds-subnet-b

  # DB Subnet Group (requires at least 2 subnets in different AZs)
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    DependsOn: SecondSubnet
    Properties:
      DBSubnetGroupDescription: Subnet group for Pipeline Pulse database
      SubnetIds:
        - subnet-fd80e6a0  # Existing default subnet (us-east-1a)
        - !Ref SecondSubnet  # New subnet (us-east-1b)
      Tags:
        - Key: Name
          Value: pipeline-pulse-db-subnet-group

  # RDS Instance
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: pipeline-pulse-db
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: '15.4'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      StorageType: gp3
      StorageEncrypted: true
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub '${StackName}-RDS-SecurityGroup-ID'
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      MultiAZ: false  # Single AZ for simplicity
      PubliclyAccessible: false
      DeletionProtection: false  # Set to false for easier cleanup during development
      DBName: pipeline_pulse
      Tags:
        - Key: Name
          Value: pipeline-pulse-database

Outputs:
  DatabaseEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DB-Endpoint'
  
  DatabasePort:
    Description: RDS instance port
    Value: !GetAtt DatabaseInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DB-Port'
