AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL for Pipeline Pulse (using proper VPC)'

Parameters:
  VPCStackName:
    Type: String
    Default: 'pipeline-pulse-vpc'
    Description: 'Name of the VPC stack to import values from'
  DBUsername:
    Type: String
    Default: 'postgres'
    Description: 'Database master username'
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'Database master password'
    MinLength: 8
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: [dev, staging, prod]

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub 'Subnet group for Pipeline Pulse database - ${Environment}'
      SubnetIds:
        - Fn::ImportValue: !Sub '${VPCStackName}-PrivateSubnet1-ID'
        - Fn::ImportValue: !Sub '${VPCStackName}-PrivateSubnet2-ID'
      Tags:
        - Key: Name
          Value: !Sub 'pipeline-pulse-db-subnet-group-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # RDS Instance
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub 'pipeline-pulse-db-${Environment}'
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: '15.13'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      StorageType: gp3
      StorageEncrypted: true
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub '${VPCStackName}-RDS-SecurityGroup-ID'
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      MultiAZ: false  # Single AZ for cost optimization in dev
      PubliclyAccessible: false
      DeletionProtection: false  # Set to false for easier cleanup during development
      DBName: pipeline_pulse
      Tags:
        - Key: Name
          Value: !Sub 'pipeline-pulse-database-${Environment}'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DatabaseEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DB-Endpoint'
  
  DatabasePort:
    Description: RDS instance port
    Value: !GetAtt DatabaseInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DB-Port'
  
  DatabaseName:
    Description: Database name
    Value: pipeline_pulse
    Export:
      Name: !Sub '${AWS::StackName}-DB-Name'
