"""v2_initial_schema

Revision ID: 68c4af5a8d13
Revises: 
Create Date: 2026-04-04 16:26:47.203652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c4af5a8d13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_territory_id'), 'accounts', ['territory_id'], unique=False)
    op.create_table('currency_rates',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('sgd_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('currency_code')
    )
    op.create_index('idx_currency_updated', 'currency_rates', ['updated_at'], unique=False)
    op.create_index(op.f('ix_currency_rates_currency_code'), 'currency_rates', ['currency_code'], unique=False)
    op.create_table('territories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_territories_id'), 'territories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'cro', 'sales_manager', 'presales_manager', 'ae', 'sdr', 'presales_consultant', 'presales_sa', 'aws_alliance_manager', 'finance_manager', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('stall_alert', 'stage_change', 'morning_brief', 'weekly_review', 'document_ready', 'approval_request', 'system', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('custodian_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('new_hunt', 'discovery', 'proposal', 'negotiation', 'order_book', name='dealstage'), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deal_value', sa.Float(), nullable=False),
    sa.Column('deal_value_sgd', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('funding_type', sa.Enum('customer', 'aws', 'dual', name='fundingtype'), nullable=False),
    sa.Column('program', sa.Enum('map', 'mmp', 'poc', 'none', name='program'), nullable=False),
    sa.Column('gtm_motion', sa.Enum('migration', 'modernisation', 'new_workload', 'managed_services', 'genai', name='gtmmotion'), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('solution_area', sa.Enum('sap', 'vmware', 'genai', 'data', 'ams', name='solutionarea'), nullable=True),
    sa.Column('ace_id', sa.String(length=100), nullable=True),
    sa.Column('map_status', sa.String(length=50), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('po_received_date', sa.Date(), nullable=True),
    sa.Column('po_id', sa.String(length=100), nullable=True),
    sa.Column('po_value_sgd', sa.Float(), nullable=True),
    sa.Column('iat_score', sa.Integer(), nullable=True),
    sa.Column('iat_qualified', sa.Boolean(), nullable=True),
    sa.Column('iat_notes', sa.Text(), nullable=True),
    sa.Column('fit_status', sa.Enum('fit', 'partial_fit', 'no_fit', 'not_evaluated', name='fitstatus'), nullable=False),
    sa.Column('fit_confidence', sa.String(length=20), nullable=True),
    sa.Column('fit_areas_matched', sa.Integer(), nullable=True),
    sa.Column('fit_signals_confirmed', sa.Integer(), nullable=True),
    sa.Column('fit_last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tco_arr_sgd', sa.Float(), nullable=True),
    sa.Column('tco_3yr_savings', sa.Float(), nullable=True),
    sa.Column('tco_current_infra_cost', sa.Float(), nullable=True),
    sa.Column('tco_migration_cost_est', sa.Float(), nullable=True),
    sa.Column('tco_net_savings_3yr', sa.Float(), nullable=True),
    sa.Column('tco_recommended_program', sa.String(length=20), nullable=True),
    sa.Column('proposal_unlocked', sa.Boolean(), nullable=False),
    sa.Column('proposal_status', sa.String(length=50), nullable=True),
    sa.Column('cro_approval_required', sa.Boolean(), nullable=False),
    sa.Column('cro_approval_granted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['custodian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_account_id'), 'opportunities', ['account_id'], unique=False)
    op.create_index(op.f('ix_opportunities_ace_id'), 'opportunities', ['ace_id'], unique=False)
    op.create_index(op.f('ix_opportunities_custodian_id'), 'opportunities', ['custodian_id'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_name'), 'opportunities', ['name'], unique=False)
    op.create_index(op.f('ix_opportunities_owner_id'), 'opportunities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_opportunities_po_id'), 'opportunities', ['po_id'], unique=False)
    op.create_index(op.f('ix_opportunities_stage'), 'opportunities', ['stage'], unique=False)
    op.create_table('ai_q_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('solution_area', sa.String(length=50), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_positive_signal', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_q_responses_id'), 'ai_q_responses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_q_responses_opportunity_id'), 'ai_q_responses', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_ai_q_responses_solution_area'), 'ai_q_responses', ['solution_area'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('sow', 'po', 'handover', 'call_notes', 'proposal', 'other', name='documenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extraction_status', sa.Enum('pending', 'ocr_running', 'extracting', 'review', 'accepted', 'rejected', name='extractionstatus'), nullable=False),
    sa.Column('textract_job_id', sa.String(length=255), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extraction_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_documents_extraction_status'), 'documents', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_opportunity_id'), 'documents', ['opportunity_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('contacted', 'engaged', 'mql_ready', 'graduated', 'disqualified', name='leadstatus'), nullable=False),
    sa.Column('icp_score', sa.Integer(), nullable=True),
    sa.Column('q_tree_completion', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('graduated_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('first_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graduated_opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_name'), 'leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('opportunity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.Enum('new_hunt', 'discovery', 'proposal', 'negotiation', 'order_book', name='dealstage'), nullable=False),
    sa.Column('deal_value_sgd', sa.Float(), nullable=False),
    sa.Column('days_in_current_stage', sa.Integer(), nullable=False),
    sa.Column('iat_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_snapshots_id'), 'opportunity_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_snapshots_opportunity_id'), 'opportunity_snapshots', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_snapshots_snapshot_date'), 'opportunity_snapshots', ['snapshot_date'], unique=False)
    op.create_table('revenue_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('expected_amount_sgd', sa.Float(), nullable=False),
    sa.Column('actual_amount_sgd', sa.Float(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'invoiced', 'paid', 'delayed', name='milestonestatus'), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_milestones_id'), 'revenue_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_milestones_opportunity_id'), 'revenue_milestones', ['opportunity_id'], unique=False)
    op.create_table('stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('stage_change', 'meeting_summary', 'note', 'document_uploaded', 'ai_insight', name='eventtype'), nullable=False),
    sa.Column('from_stage', sa.Enum('new_hunt', 'discovery', 'proposal', 'negotiation', 'order_book', name='dealstage'), nullable=True),
    sa.Column('to_stage', sa.Enum('new_hunt', 'discovery', 'proposal', 'negotiation', 'order_book', name='dealstage'), nullable=True),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_events_event_type'), 'stage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stage_events_id'), 'stage_events', ['id'], unique=False)
    op.create_index(op.f('ix_stage_events_opportunity_id'), 'stage_events', ['opportunity_id'], unique=False)
    op.create_table('tco_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('server_count', sa.Integer(), nullable=True),
    sa.Column('vm_count', sa.Integer(), nullable=True),
    sa.Column('storage_tb', sa.Float(), nullable=True),
    sa.Column('network_egress_tb_month', sa.Float(), nullable=True),
    sa.Column('current_licence_spend_sgd', sa.Float(), nullable=True),
    sa.Column('migration_type', sa.String(length=50), nullable=True),
    sa.Column('ps_estimate_sgd', sa.Float(), nullable=True),
    sa.Column('support_tier', sa.String(length=50), nullable=True),
    sa.Column('arr_sgd', sa.Float(), nullable=True),
    sa.Column('savings_3yr_sgd', sa.Float(), nullable=True),
    sa.Column('migration_cost_sgd', sa.Float(), nullable=True),
    sa.Column('net_savings_3yr_sgd', sa.Float(), nullable=True),
    sa.Column('recommended_program', sa.String(length=20), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tco_sessions_id'), 'tco_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_tco_sessions_opportunity_id'), 'tco_sessions', ['opportunity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tco_sessions_opportunity_id'), table_name='tco_sessions')
    op.drop_index(op.f('ix_tco_sessions_id'), table_name='tco_sessions')
    op.drop_table('tco_sessions')
    op.drop_index(op.f('ix_stage_events_opportunity_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_event_type'), table_name='stage_events')
    op.drop_table('stage_events')
    op.drop_index(op.f('ix_revenue_milestones_opportunity_id'), table_name='revenue_milestones')
    op.drop_index(op.f('ix_revenue_milestones_id'), table_name='revenue_milestones')
    op.drop_table('revenue_milestones')
    op.drop_index(op.f('ix_opportunity_snapshots_snapshot_date'), table_name='opportunity_snapshots')
    op.drop_index(op.f('ix_opportunity_snapshots_opportunity_id'), table_name='opportunity_snapshots')
    op.drop_index(op.f('ix_opportunity_snapshots_id'), table_name='opportunity_snapshots')
    op.drop_table('opportunity_snapshots')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_name'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_documents_opportunity_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_extraction_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ai_q_responses_solution_area'), table_name='ai_q_responses')
    op.drop_index(op.f('ix_ai_q_responses_opportunity_id'), table_name='ai_q_responses')
    op.drop_index(op.f('ix_ai_q_responses_id'), table_name='ai_q_responses')
    op.drop_table('ai_q_responses')
    op.drop_index(op.f('ix_opportunities_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_po_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_owner_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_name'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_custodian_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_ace_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_account_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_territories_id'), table_name='territories')
    op.drop_table('territories')
    op.drop_index(op.f('ix_currency_rates_currency_code'), table_name='currency_rates')
    op.drop_index('idx_currency_updated', table_name='currency_rates')
    op.drop_table('currency_rates')
    op.drop_index(op.f('ix_accounts_territory_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
