"""Add region to CrmRecord

Revision ID: 99b1869406bf
Revises: 010
Create Date: 2025-07-17 20:41:16.813890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '99b1869406bf'
down_revision = '010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add region column to crm_records table
    op.add_column('crm_records', sa.Column('region', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_crm_records_region'), 'crm_records', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove region column from crm_records table
    op.drop_index(op.f('ix_crm_records_region'), table_name='crm_records')
    op.drop_column('crm_records', 'region')
    # ### end Alembic commands ###
