"""Add zoho_oauth_tokens table for multi-user Zoho SDK integration

Revision ID: b81de42e3df8
Revises: a019c2898f48
Create Date: 2025-07-05 14:51:12.670643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81de42e3df8'
down_revision: Union[str, None] = 'a019c2898f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoho_oauth_tokens',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('grant_token', sa.String(), nullable=True),
    sa.Column('expiry_time', sa.BigInteger(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('api_domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_index(op.f('ix_zoho_oauth_tokens_user_email'), 'zoho_oauth_tokens', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoho_oauth_tokens_user_email'), table_name='zoho_oauth_tokens')
    op.drop_table('zoho_oauth_tokens')
    # ### end Alembic commands ###