"""Add Zoho OAuth token table for SDK persistence

Revision ID: fa0d40278ce9
Revises: 015_add_sync_operations_tables
Create Date: 2025-07-04 11:21:10.985775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fa0d40278ce9'
down_revision = '015_add_sync_operations_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('oauthtokens',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('grant_token', sa.String(length=255), nullable=True),
    sa.Column('expiry_time', sa.String(length=20), nullable=True),
    sa.Column('redirect_url', sa.String(length=255), nullable=True),
    sa.Column('api_domain', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    op.drop_table('oauthtokens')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoho_token_records_id'), table_name='zoho_token_records')
    op.create_index(op.f('idx_token_records_id'), 'zoho_token_records', ['id'], unique=False)
    op.drop_index(op.f('ix_zoho_oauth_tokens_user_name'), table_name='zoho_oauth_tokens')
    op.drop_index(op.f('ix_zoho_oauth_tokens_client_id'), table_name='zoho_oauth_tokens')
    op.create_index(op.f('idx_zoho_tokens_user'), 'zoho_oauth_tokens', ['user_name'], unique=False)
    op.create_index(op.f('idx_zoho_tokens_client'), 'zoho_oauth_tokens', ['client_id'], unique=False)
    op.add_column('users', sa.Column('job_title', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('zoho_role', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('last_activity', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('locale', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('api_quota_used', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('preferences', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('role_cache_expires', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('api_quota_reset', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('zoho_permissions', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_users_zoho_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_zoho_user_id'), 'users', ['zoho_user_id'], unique=1)
    op.create_index(op.f('idx_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'role_cache_valid_until')
    op.drop_column('users', 'last_role_sync')
    op.drop_column('users', 'territory_assignments')
    op.drop_column('users', 'field_permissions')
    op.drop_column('users', 'module_permissions')
    op.drop_column('users', 'zoho_profile_name')
    op.drop_column('users', 'zoho_profile_id')
    op.drop_column('users', 'zoho_role_name')
    op.drop_column('users', 'zoho_role_id')
    op.drop_index(op.f('ix_user_states_id'), table_name='user_states')
    op.create_index(op.f('ix_user_states_user_id_active'), 'user_states', ['user_id', 'is_active'], unique=False)
    op.add_column('user_sessions', sa.Column('refresh_token', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user_sessions', sa.Column('last_activity', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user_sessions', sa.Column('device_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user_sessions', sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
    op.add_column('user_sessions', sa.Column('expires_at', sa.DATETIME(), nullable=False))
    op.add_column('user_sessions', sa.Column('session_token', sa.VARCHAR(length=255), nullable=False))
    op.add_column('user_sessions', sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True))
    op.add_column('user_sessions', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.create_index(op.f('idx_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=1)
    op.create_index(op.f('idx_user_sessions_active'), 'user_sessions', ['is_active'], unique=False)
    op.alter_column('user_sessions', 'token_expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_sessions', 'zoho_refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_sessions', 'zoho_access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('user_sessions', 'last_used')
    op.drop_column('user_sessions', 'session_permissions')
    op.drop_index(op.f('ix_token_refresh_logs_token_record_id'), table_name='token_refresh_logs')
    op.drop_index(op.f('ix_token_refresh_logs_id'), table_name='token_refresh_logs')
    op.create_index(op.f('idx_token_refresh_logs_token_id'), 'token_refresh_logs', ['token_record_id'], unique=False)
    op.drop_index(op.f('ix_token_alerts_token_record_id'), table_name='token_alerts')
    op.drop_index(op.f('ix_token_alerts_id'), table_name='token_alerts')
    op.create_index(op.f('idx_token_alerts_token_id'), 'token_alerts', ['token_record_id'], unique=False)
    op.create_index(op.f('idx_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.add_column('sync_status_logs', sa.Column('estimated_completion', sa.DATETIME(), nullable=True))
    op.add_column('sync_status_logs', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('sync_status_logs', sa.Column('records_processed', sa.INTEGER(), nullable=True))
    op.add_column('sync_status_logs', sa.Column('progress_percentage', sa.FLOAT(), nullable=True))
    op.add_column('sync_status_logs', sa.Column('current_operation', sa.VARCHAR(length=255), nullable=True))
    op.add_column('sync_status_logs', sa.Column('status', sa.VARCHAR(length=50), nullable=False))
    op.add_column('sync_status_logs', sa.Column('details', sqlite.JSON(), nullable=True))
    op.drop_constraint(None, 'sync_status_logs', type_='foreignkey')
    op.drop_index(op.f('ix_sync_status_logs_id'), table_name='sync_status_logs')
    op.create_index(op.f('idx_sync_status_logs_session_id'), 'sync_status_logs', ['session_id'], unique=False)
    op.alter_column('sync_status_logs', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sync_status_logs', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('sync_status_logs', 'error_details')
    op.drop_column('sync_status_logs', 'error_code')
    op.drop_column('sync_status_logs', 'data_payload')
    op.drop_column('sync_status_logs', 'execution_time_ms')
    op.drop_column('sync_status_logs', 'api_endpoint')
    op.drop_column('sync_status_logs', 'record_id')
    op.drop_column('sync_status_logs', 'component')
    op.drop_column('sync_status_logs', 'log_level')
    op.add_column('sync_health_metrics', sa.Column('webhook_events_received', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('average_sync_duration', sa.FLOAT(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('performance_score', sa.FLOAT(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('alerts_triggered', sqlite.JSON(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('api_quota_remaining', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('health_status', sa.VARCHAR(length=50), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('failed_syncs', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('total_records_synced', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('conflict_count', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('api_calls_made', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('successful_syncs', sa.INTEGER(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('error_rate_percentage', sa.FLOAT(), nullable=True))
    op.add_column('sync_health_metrics', sa.Column('total_syncs', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_sync_health_metrics_metric_date'), table_name='sync_health_metrics')
    op.drop_index(op.f('ix_sync_health_metrics_id'), table_name='sync_health_metrics')
    op.create_index(op.f('idx_sync_health_metrics_date'), 'sync_health_metrics', ['metric_date'], unique=False)
    op.drop_column('sync_health_metrics', 'uptime_percentage')
    op.drop_column('sync_health_metrics', 'system_health_score')
    op.drop_column('sync_health_metrics', 'data_freshness_minutes')
    op.drop_column('sync_health_metrics', 'total_validation_errors')
    op.drop_column('sync_health_metrics', 'avg_data_quality_score')
    op.drop_column('sync_health_metrics', 'total_data_transferred_mb')
    op.drop_column('sync_health_metrics', 'avg_response_time_ms')
    op.drop_column('sync_health_metrics', 'total_rate_limit_hits')
    op.drop_column('sync_health_metrics', 'total_api_calls')
    op.drop_column('sync_health_metrics', 'avg_processing_time_ms')
    op.drop_column('sync_health_metrics', 'total_conflicts_detected')
    op.drop_column('sync_health_metrics', 'total_records_failed')
    op.drop_column('sync_health_metrics', 'total_records_successful')
    op.drop_column('sync_health_metrics', 'total_records_processed')
    op.drop_column('sync_health_metrics', 'avg_session_duration_seconds')
    op.drop_column('sync_health_metrics', 'failed_sessions')
    op.drop_column('sync_health_metrics', 'successful_sessions')
    op.drop_column('sync_health_metrics', 'total_sessions')
    op.drop_column('sync_health_metrics', 'module_name')
    op.add_column('sync_configurations', sa.Column('enable_webhooks', sa.BOOLEAN(), nullable=True))
    op.add_column('sync_configurations', sa.Column('filters', sqlite.JSON(), nullable=True))
    op.add_column('sync_configurations', sa.Column('conflict_resolution_strategy', sa.VARCHAR(length=50), nullable=True))
    op.add_column('sync_configurations', sa.Column('webhook_events', sqlite.JSON(), nullable=True))
    op.add_column('sync_configurations', sa.Column('modules_to_sync', sqlite.JSON(), nullable=True))
    op.add_column('sync_configurations', sa.Column('max_retry_attempts', sa.INTEGER(), nullable=True))
    op.add_column('sync_configurations', sa.Column('notification_settings', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_sync_configurations_id'), table_name='sync_configurations')
    op.drop_index(op.f('ix_sync_configurations_config_name'), table_name='sync_configurations')
    op.create_index(op.f('idx_sync_configurations_active'), 'sync_configurations', ['is_active'], unique=False)
    op.alter_column('sync_configurations', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('sync_configurations', 'batch_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_configurations', 'sync_frequency_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_configurations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sync_configurations', 'config_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('sync_configurations', 'failure_threshold_percentage')
    op.drop_column('sync_configurations', 'alert_on_failures')
    op.drop_column('sync_configurations', 'timeout_seconds')
    op.drop_column('sync_configurations', 'max_concurrent_operations')
    op.drop_column('sync_configurations', 'rate_limit_buffer')
    op.drop_column('sync_configurations', 'quality_thresholds')
    op.drop_column('sync_configurations', 'validation_rules')
    op.drop_column('sync_configurations', 'field_specific_resolutions')
    op.drop_column('sync_configurations', 'default_conflict_resolution')
    op.drop_column('sync_configurations', 'readonly_fields')
    op.drop_column('sync_configurations', 'required_fields')
    op.drop_column('sync_configurations', 'module_name')
    op.drop_index(op.f('ix_state_change_logs_id'), table_name='state_change_logs')
    op.create_index(op.f('ix_state_change_logs_user_id_type'), 'state_change_logs', ['user_id', 'change_type'], unique=False)
    op.create_index(op.f('ix_state_change_logs_sync_id'), 'state_change_logs', ['sync_id'], unique=False)
    op.add_column('crm_sync_sessions', sa.Column('error_details', sqlite.JSON(), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('session_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('filters_applied', sqlite.JSON(), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('operation_type', sa.VARCHAR(length=50), nullable=False))
    op.add_column('crm_sync_sessions', sa.Column('sync_trigger', sa.VARCHAR(length=100), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('performance_metrics', sqlite.JSON(), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('total_records_processed', sa.INTEGER(), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('sync_scope', sqlite.JSON(), nullable=True))
    op.add_column('crm_sync_sessions', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index(op.f('ix_crm_sync_sessions_status'), table_name='crm_sync_sessions')
    op.drop_index(op.f('ix_crm_sync_sessions_session_type'), table_name='crm_sync_sessions')
    op.drop_index(op.f('ix_crm_sync_sessions_id'), table_name='crm_sync_sessions')
    op.create_index(op.f('idx_crm_sync_sessions_status'), 'crm_sync_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_crm_sync_sessions_started_at'), 'crm_sync_sessions', ['started_at'], unique=False)
    op.alter_column('crm_sync_sessions', 'skipped_records',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crm_sync_sessions', 'failed_records',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crm_sync_sessions', 'successful_records',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crm_sync_sessions', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('crm_sync_sessions', 'status',
               existing_type=sa.Enum('INITIATED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='syncsessionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
